
<!--******************-->
<!--                  -->
<!--    PROJECTS      -->
<!--                  -->
<!--******************-->
 
<!-- end Preview -->
<span id="projects"></span>
<h1 id="recentProjects">Recent Projects</h1>

<div id="projectShowcase">

    <!-- example fancybox wraps:

<a class="fancybox" rel="group" href="big_image_1.jpg"><img alt="" src="small_image_1.jpg" alt="" /></a>
<a class="fancybox" rel="group" href="big_image_2.jpg"><img alt="" src="small_image_2.jpg" alt="" /></a>

-->

    <!--PROJECTS SHOW -->
    <div class="projects">


        <div class="projContainer">
            <a class="fancybox" rel="group" href="img/thumbnails/bookshelf.png" title="<h2>Bookshelf</h2>An interactive ebook library<br><br>PHP, JS, SQL <br/><a class='links' target='_blank' href='http://bookshelf.isobellennox.com'>View This Project</a>"><img alt="Escape Hatch" src="img/thumbnails/bookshelf.png" />
                <div class="projInfoContainer">
                    <h2>Bookshelf</h2>
                    <p class="projCat">PHP, JS, SQL</p>
                    <p class="projSpec">Interactive Library
                        <br/>Personal Development
                        <br />
                        <!--Click to see more details</p>
 -->
                </div>
            </a>
            <!-- # -->
        </div>


        <div class="projContainer">
            <a class="fancybox" rel="group" href="img/thumbnails/arbytes.png" title="<h2>Arbytes</h2>A Ticketing and Content Management System<br> built from scratch to sharpen skills with database design<br>PHP, JS, SQL <br/><a class='links' target='_blank' href='http://arbytes.isobellennox.com'>View This Project</a>"><img alt="Escape Hatch" src="img/thumbnails/arbytes.png" />
                <div class="projInfoContainer">
                    <h2>Arbytes</h2>
                    <p class="projCat">PHP, JS, SQL</p>
                    <p class="projSpec">Ticketing/CMS Website
                        <br/>Winter 2015 CTEC290 Project
                        <br />
                        <!--Click to see more details</p>
 -->
                </div>
            </a>
            <!-- # -->
        </div>
        
        
        <div class="projContainer">
            <a class="fancybox" rel="group" href="img/thumbnails/EH.png" title="<h2>EscapeHatch</h2>A Social Media Network<br> built from scratch to sharpen skills with database design<br>PHP, JS, SQL <br/><a class='links' target='_blank' href='http://ehv1.isobellennox.com'>View This Project</a>"><img alt="Escape Hatch" src="img/thumbnails/EH.png" />
                <div class="projInfoContainer">
                    <h2>EscapeHatch</h2>
                    <p class="projCat">PHP, JS, SQL</p>
                    <p class="projSpec">Social Media Website
                        <br/>Personal Development Project
                        <br />
                        <!--Click to see more details</p>
 -->
                </div>
            </a>
            <!-- # -->
        </div>
 

        <div class="projContainer">
            <a class="fancybox" rel="group" href="img/thumbnails/ctec127.PNG" title="<h2>PHP/SQL Final</h2>This project emphasizes simple admin panel controls:<br/> PHP, MySQL, and JS <br/><a class='links' target='_blank' href='http://ctec127.isobellennox.com'>View in a new tab.</a>"><img alt="" src="img/thumbnails/ctec127.PNG" />
                <div class="projInfoContainer">
                    <h2>PHP & SQL Final</h2>
                    <p class="projCat"> PHP, MySQL, JS</p>
                    <p class="projSpec">
                        <br />
                    </p>
                </div>
            </a>
            <!-- projects/jsFinalProject/index.php -->
        </div>
        
        

        <div class="projContainer">
            <a class="fancybox" rel="group" href="img/thumbnails/jsFinal.png" title="<h2>Javascript Final</h2>This project includes technologies learned in CTEC126:<br/> Ajax, APIs, JSON, jQuery <br/><a class='links' target='_blank' href='projects/jsFinalProject/index.php'>View in a new tab.</a>"><img alt="" src="img/thumbnails/jsFinal.png" />
                <div class="projInfoContainer">
                    <h2>Javascript Final</h2>
                    <p class="projCat"> Ajax, APIs, JSON, jQuery</p>
                    <p class="projSpec">
                        <br />
                    </p>
                </div>
            </a>
            <!-- projects/jsFinalProject/index.php -->
        </div>


        <div class="projContainer">
            <a class="fancybox" rel="group" href="img/thumbnails/animations.PNG" title="<h2>jQuery Animation</h2>A presentation for CTEC126: Javascript <br/>Illustrating the differences in animations using CSS3 vs. jQuery.<br/> View Codepen for full CSS3 vs. jQuery presentation.<br/><a class='links' target='_blank' href='projects/jqueryAnimation/index.php'>View in a new tab.</a>"><img alt="" src="img/thumbnails/animations.PNG" />
                <div class="projInfoContainer">
                    <h2>Animations</h2>
                    <p class="projCat">jQuery
                        <!--/ CSS3-->
                    </p>
                    <p class="projSpec">Simple jQuery Animation
                        <br />
                    </p>
                </div>
            </a>
            <!-- projects/jqueryAnimation/index.php -->
        </div>



        <div class="projContainer">
            <a class="fancybox" rel="group" href="img/thumbnails/BusWebFinal.png" title="<h2>Business Web Practices Final</h2>This is a five-part essay based on the employed ethics and<br/> legal concerns applied to web development technologies.<br/> Completed for CTEC165: Business Web Practices.<br/><a class='links' target='_blank' href='projects/BusWebFinalExam/index.php'>View in a new tab.</a>"><img alt="" src="img/thumbnails/BusWebFinal.png" />
                <div class="projInfoContainer">
                    <h2>Business Web Practices Final</h2>
                    <p class="projCat"> Essay </p>
                    <p class="projSpec">
                        <br/>
                    </p>
                </div>
            </a>
            <!-- projects/BusWebFinalExam/index.php -->
        </div>


        <div class="projContainer">
            <a class="fancybox" rel="group" href="img/thumbnails/codepen.png" title="<h2>Codepen</h2>A collection of code snippets. <br/><a class='links' target='_blank' href='http://codepen.io/IsoLennox/public/'>Visit Isobel Lennox on codepen</a>."><img alt="" src="img/thumbnails/codepen.png" />
                <div class="projInfoContainer">
                    <h2>Codepen</h2>
                    <p class="projCat">PHP, JS, CSS3</p>
                    <p class="projSpec">A collection of code snippets.
                        <br />
                        <!--Click to see more details.-->
                    </p>
                </div>
            </a>
            <!--http://codepen.io/IsoLennox/public/-->
        </div>



        <div class="projContainer">
            <a class="fancybox" rel="group" href="img/thumbnails/lennoxfiles.png" title="<h2>LennoXfiles Blog</h2>A Computer Technology tutorial and reference blog<br/> written by Isobel Lennox.<br/><a class='links' target='_blank' href='http://lennoxfiles.wordpress.com'>View in a new tab.</a>"><img alt="" src="img/thumbnails/lennoxfiles.png" />
                <div class="projInfoContainer">
                    <h2>LennoXfiles Blog</h2>
                    <p class="projCat">Reference and Tutorial</p>
                    <p class="projSpec">A Computer Technology tutorial and reference blog.
                        <br />
                    </p>
                </div>
            </a>
            <!-- http://lennoxfiles.wordpress.com -->
        </div>


        <!-- FUTURE PROJECTS 


         <div class="projContainer">
  <a class="fancybox" rel="group" href="img/thumbnails/comingsoon.png" title="<h2>PHP Classwork</h2>Compliation of CTEC 127 Projects during Class."><img alt="" src="img/thumbnails/comingsoon.png" />
  <div class="projInfoContainer">
    <h2>PHP Classwork</h2>
    <p class="projCat"> PHP, SQL</p>
    <p class="projSpec">CTEC 127 Projects during Class.<br /></p>
  </div></a>
</div>
           
            
         <div class="projContainer">
  <a class="fancybox" rel="group" href="img/thumbnails/comingsoon.png" title="<h2></h2>"><img alt="" src="img/thumbnails/comingsoon.png" />
  <div class="projInfoContainer">
    <h2>PHP 1 Final Project</h2>
    <p class="projCat">PHP, SQL</p>
    <p class="projSpec">Winter 2015 CTEC127<br /></p>
  </div></a>
</div>
           
            
            <div class="projContainer">
  <a class="fancybox" rel="group" href="img/thumbnails/comingsoon.png" title="<h2></h2>"><img alt="" src="img/thumbnails/comingsoon.png" />
  <div class="projInfoContainer">
    <h2>CTEC 290</h2>
    <p class="projCat">Tech</p>
    <p class="projSpec">Spring 2015 CTEC290 Project.<br /></p>
  </div></a>
</div>
           
             <div class="projContainer">
  <a class="fancybox" rel="group" href="img/thumbnails/comingsoon.png" title="<h2></h2>"><img alt="" src="img/thumbnails/comingsoon.png" />
  <div class="projInfoContainer">
    <h2>PHP 2 Final Project</h2>
    <p class="projCat">PHP, SQL</p>
    <p class="projSpec">Spring 2015 CTEC227<br /></p>
  </div></a>
</div>
            
             END FUTURE PROJECTS -->




    </div>
    <!-- END BETTER PROJECTS SHOW-->

</div>
<!-- end showcase -->